[package]
name = "yzix-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-Exception"

[dependencies]
base64 = "0.13"

[dependencies.camino]
version = "1.0"
features = ["serde1"]

[dependencies.petgraph]
version = "0.6"
default-features = false
features = ["serde-1"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive", "std"]
