[package]
name = "yzix-server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
async-channel = "1.6"
async-ctrlc = "1.2"
async-lock = "2.4"
async-net = "1.6"
async-process = "1.3"
bit-set = "0.5.2"
clap = "2.34"
futures-lite = "1.12"
indicatif = "0.16"
num_cpus = "1.13"
once_cell = "1.8.0"
serde = "1.0"
tempfile = "3.2"
thiserror = "1.0.30"
yz-server-executor = "0.2"

[dependencies.yzix-core]
path = "../yzix-core"
